### ISSUE TITLE
[Algo] Bubble Sort [Python]

### ISSUE THREAD

**Issue by sangamcse** [NITSkmOS/Algorithms#13]

**Comment by moximo13** [comment]
> _No description provided._

add bubblesort in python #113

**Comment by sangamcse** [comment]
Do not open PR without the assignment. There are multiple PR for one issue and I'm going to reject them all.

**Comment by anubhav4sachan** [comment]
I want to take it. @sangamcse bhaiya, Can you assign it to me?

**Comment by sangamcse** [comment]
@anubhav4sachan, @swapsha96 has already done in #85 PR

**Comment by mariush2** [comment]
Please assign me this issue

**Comment by sangamcse** [comment]
@mariush2 the issue is already assigned to @swapsha96. Find some unassigned issues.

**Comment by sameerchoubey** [comment]
@sangamcse  Please assign this issue to me.
