### ISSUE TITLE
[Algo] Shell Sort [Python]

### ISSUE THREAD

**Issue by sangamcse** [NITSkmOS/Algorithms#133]
https://en.wikipedia.org/wiki/Shellsort

**Comment by sangamcse** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by JonathanGin52** [comment]
I'll take this one!

**Comment by sangamcse** [comment]
@JonathanGin52, sorry, this one is already taken by @anubhav4sachan. Choose another. Thank you.
