### ISSUE TITLE
[Algo] Shell Sort [C]

### ISSUE THREAD

**Issue by sangamcse** [NITSkmOS/Algorithms#135]
https://en.wikipedia.org/wiki/Shellsort

**Comment by sangamcse** [comment]
@gitmate-bot

**Comment by bihanviranga** [comment]
Shall I start on this one?

**Comment by sangamcse** [comment]
Sure. Please go through the commit guidelines before opening PR.

**Comment by bihanviranga** [comment]
Thank you. Can you please assign this to me?
