### ISSUE TITLE
[Algo] Merge Sort [C]

### ISSUE THREAD

**Issue by 123vivekr** [NITSkmOS/Algorithms#147]
https://en.wikipedia.org/wiki/Merge_sort

**Comment by 123vivekr** [comment]
Please assign this to me

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/145 ([Algo] Selection Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/146 ([Algo] Quick Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/23 ([Algo]: Add Heapsort in C), https://github.com/NITSkmOS/Algorithms/issues/44 ([Algo] Binary Search [C]), and https://github.com/NITSkmOS/Algorithms/issues/135 ([Algo] Shell Sort [C]).

**Comment by 123vivekr** [comment]
@sangamcse I did not understand your last message. 
Merge Sort for C is not implemented nor there is any issue up for its implementation AFAIK

**Comment by sangamcse** [comment]
Don't worry about that. I have already assigned you for the issue. That message is just bot analysis of whole repository.
