### ISSUE TITLE
[Algo] Merge Sort [Java]

### ISSUE THREAD

**Issue by udayvig** [NITSkmOS/Algorithms#149]
https://en.wikipedia.org/wiki/Merge_sort

Please assign this to me.

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/21 ([Algo]: Add Heapsort in Java), https://github.com/NITSkmOS/Algorithms/issues/46 ([Algo] Binary Search [Java]), https://github.com/NITSkmOS/Algorithms/issues/18 ([Algo]: Add Bubble Sort in Java), https://github.com/NITSkmOS/Algorithms/issues/63 ([Algo] Insertion Sort [Java]), and https://github.com/NITSkmOS/Algorithms/issues/134 ([Algo] Shell Sort [Java]).

**Comment by vishnoitanuj** [comment]
I have added a PR to Mere sort in java. Please check it. Thanks for involving participation @udayvig

**Comment by udayvig** [comment]
> I have added a PR to Mere sort in java. Please check it. Thanks for involving participation @udayvig

Oh, I must have missed that. Sorry.

**Comment by sangamcse** [comment]
@fedesassone still waiting for you to accept the invitation.

**Comment by sangamcse** [comment]
@fedesassone assigned. Also, don't forget to read CONTRIBUTING.md documentation before opening a PR.
