### ISSUE TITLE
[Algo] Quick Sort [Java]

### ISSUE THREAD

**Issue by udayvig** [NITSkmOS/Algorithms#150]
https://en.wikipedia.org/wiki/Quicksort

Please assign this to me.

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/149 ([Algo] Merge Sort [Java]), https://github.com/NITSkmOS/Algorithms/issues/18 ([Algo]: Add Bubble Sort in Java), https://github.com/NITSkmOS/Algorithms/issues/46 ([Algo] Binary Search [Java]), https://github.com/NITSkmOS/Algorithms/issues/21 ([Algo]: Add Heapsort in Java), and https://github.com/NITSkmOS/Algorithms/issues/63 ([Algo] Insertion Sort [Java]).

**Comment by vishnoitanuj** [comment]
I have added a PR to this issue. Please check it. Thanks for giving the opportunity to participate!!

**Comment by udayvig** [comment]
> I have added a PR to this issue. Please check it. Thanks for giving the opportunity to participate!!

I opened these issues for myself, was waiting to be assigned before which you added the PR.

**Comment by sangamcse** [comment]
@udayvig, Please read Contribution guidelines before opening any PR.

**Comment by sangamcse** [comment]
@vishnoitanuj and @udayvig, ask for assignment before starting working on any issue. Read the contribution guideline before contribution to any organisation.

**Comment by udayvig** [comment]
> @vishnoitanuj and @udayvig, ask for assignment before starting working on any issue. Read the contribution guideline before contribution to any organisation.

I did read them, will read them more carefully from now on. Sorry for the inconvenience caused.

**Comment by vishnoitanuj** [comment]
Okay sorry sir. Had not read the contribution guidelines.
Sorry for the inconvenience caused.
