### ISSUE TITLE
[Algo] Insertion Sort [Java]

### ISSUE THREAD

**Issue by udayvig** [NITSkmOS/Algorithms#153]
https://en.wikipedia.org/wiki/Insertion_sort

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/63 ([Algo] Insertion Sort [Java]), https://github.com/NITSkmOS/Algorithms/issues/149 ([Algo] Merge Sort [Java]), https://github.com/NITSkmOS/Algorithms/issues/145 ([Algo] Selection Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/46 ([Algo] Binary Search [Java]), and https://github.com/NITSkmOS/Algorithms/issues/150 ([Algo] Quick Sort [Java]).

**Comment by sangamcse** [comment]
Duplicate of https://github.com/NITSkmOS/Algorithms/issues/63
