### ISSUE TITLE
euclidean_gcd in c++

### ISSUE THREAD

**Issue by thakurdivyanshu** [NITSkmOS/Algorithms#186]
euclidean__gcd is there in c & java only. It should be there in c++ as well !!

**Comment by thakurdivyanshu** [comment]
can i work on this??

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/16 ([Algo]: Add euclidean-gcd in C++), https://github.com/NITSkmOS/Algorithms/issues/20 ([Algo]: Add Bubble Sort in C++), https://github.com/NITSkmOS/Algorithms/issues/41 ([DataStructure] Stack [C++]), https://github.com/NITSkmOS/Algorithms/issues/27 ([DataStructure] Linear Linked List [C++]), and https://github.com/NITSkmOS/Algorithms/issues/32 ([DataStructure] Doubly Linked List [C++]).

**Comment by sangamcse** [comment]
Duplicate of https://github.com/NITSkmOS/Algorithms/issues/16
