### ISSUE TITLE
Remove Codacy Badge and Include Travis Badge in README

### ISSUE THREAD

**Issue by sangamcse** [NITSkmOS/Algorithms#209]
Travis Badge
```
[![Build Status](https://travis-ci.com/NITSkmOS/Algorithms.svg?branch=master)](https://travis-ci.com/NITSkmOS/Algorithms)
```

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/24 (Remove `ISSUE_TEMPLATE`), and https://github.com/NITSkmOS/Algorithms/issues/199 (Start Travis Build).

**Comment by paawan01** [comment]
I'd volunteer for this !

**Comment by beingadityak** [comment]
@paawan01 are you working on this? If not, then @sangamcse can you please assign this to me?

**Comment by sangamcse** [comment]
Wait for @paawan01 reply. Remind me on gitter.

**Comment by paawan01** [comment]
@beingadityak Yup. I'll be making a PR soon.
