### ISSUE TITLE
[Data Structure] Fenwick Tree [CPP]

### ISSUE THREAD

**Issue by nick41746** [NITSkmOS/Algorithms#214]
https://en.wikipedia.org/wiki/Fenwick_tree

I want to implement this data structure in cpp.

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/47 ([Data Structure] AVL Tree [C]), https://github.com/NITSkmOS/Algorithms/issues/56 ([Data Structure] Queue [C]), https://github.com/NITSkmOS/Algorithms/issues/50 ([Data Structure] AVL Tree [Python]), https://github.com/NITSkmOS/Algorithms/issues/53 ([Data Structure] Binary Search Tree [C]), and https://github.com/NITSkmOS/Algorithms/issues/49 ([Data Structure] AVL Tree [Java]).

**Comment by abhishalya** [comment]
I could implement this :)
Can you assign this issue to me?

**Comment by sangamcse** [comment]
@abhishalya, @nick41746 asked for the assignment first.
