### ISSUE TITLE
[Algorithm] Maximum SubArray Problem [Python]

### ISSUE THREAD

**Issue by halderjoydeep** [NITSkmOS/Algorithms#215]
I want to implement Maximum SubArray problem in Python. May  I proceed?

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/183 ([Algo] Dijkstra’s Shortest Path Algorithm [Python]), https://github.com/NITSkmOS/Algorithms/issues/37 ([DataStructure] Stack [Python]), https://github.com/NITSkmOS/Algorithms/issues/2 (Add all sorting algorithms), https://github.com/NITSkmOS/Algorithms/issues/43 ([Algo] Binary Search [Python]), and https://github.com/NITSkmOS/Algorithms/issues/13 ([Algo]: Add Bubble Sort in python).

**Comment by sangamcse** [comment]
Where is the reference of the Algo? Like wiki or any other.

**Comment by halderjoydeep** [comment]
Here is the reference of maximum subarray problem.
[https://en.wikipedia.org/wiki/Maximum_subarray_problem](url)

**Comment by udaykiranreddykondreddy** [comment]
I submitted a PR but Labelled as Invalid please check

**Comment by sangamcse** [comment]
@udaykiranreddykondreddy because you opened a PR without asking any assignment of issue and @halderjoydeep has already asked for the assignment first https://github.com/NITSkmOS/Algorithms/issues/215#issue-366332014

**Comment by sangamcse** [comment]
@halderjoydeep go through the contribution guidelines before opening a PR

**Comment by udaykiranreddykondreddy** [comment]
sorry
