### ISSUE TITLE
[Data Structure] Fenwick Tree [Java]

### ISSUE THREAD

**Issue by SnowyCoder** [NITSkmOS/Algorithms#218]
The FenwickTree is a data structure for O(log(n)) updates and queries that answers both point-update and range-query questions, find out more here: https://en.wikipedia.org/wiki/Fenwick_tree
It would be nice to have this data structure implemented in Java (that is used a lot in programming contexts)

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/214 ([Data Structure] Fenwick Tree [CPP]), https://github.com/NITSkmOS/Algorithms/issues/49 ([Data Structure] AVL Tree [Java]), https://github.com/NITSkmOS/Algorithms/issues/52 ([Data Structure] Binary Search Tree [Java]), https://github.com/NITSkmOS/Algorithms/issues/57 ([Data Structure] Queue [Java]), and https://github.com/NITSkmOS/Algorithms/issues/56 ([Data Structure] Queue [C]).
