### ISSUE TITLE
[Data Structure] Fenwick Tree [Python] 

### ISSUE THREAD

**Issue by SnowyCoder** [NITSkmOS/Algorithms#220]
The FenwickTree is a data structure for O(log(n)) updates and queries that answers both point-update and range-query questions, find out more here: https://en.wikipedia.org/wiki/Fenwick_tree
It would be nice to have this data structure implemented in Python.

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/50 ([Data Structure] AVL Tree [Python]), https://github.com/NITSkmOS/Algorithms/issues/214 ([Data Structure] Fenwick Tree [CPP]), https://github.com/NITSkmOS/Algorithms/issues/51 ([Data Structure] Binary Search Tree [Python]), https://github.com/NITSkmOS/Algorithms/issues/55 ([Data Structure] Queue [Python]), and https://github.com/NITSkmOS/Algorithms/issues/218 ([Data Structure] Fenwick Tree [Java]).

**Comment by buddhikac96** [comment]
i'm work on this issue

**Comment by sanghisha145** [comment]
Can I work on this?

**Comment by sangamcse** [comment]
@buddhikac96 and @sanghisha145 you can see that there is one PR open for this issue. So please find unassigned issue.

**Comment by sanghisha145** [comment]
@sangamcse can you tell how to find unassigned issue, since I checked Issues and under Assignee, when I clicked on Assigned to Nobody, but still someone has already submitted their code. ?
