### ISSUE TITLE
Remove `ISSUE_TEMPLATE`

### ISSUE THREAD

**Issue by sangamcse** [NITSkmOS/Algorithms#24]
Remove `ISSUE_TEMPLATE` from `.github` directory.

**Comment by flamespt** [comment]
The only thing to be done here is removing the ISSUE_TEMPLATE folder from .github? Can you assign to me?

**Comment by shreyasbapat** [comment]
Solved in #42

**Comment by sangamcse** [comment]
@shreyasbapat, reviewed it. 😉  Also, do ask for assignment before opening PR. Thank you.

**Comment by shreyasbapat** [comment]
Yeah! Changed!
