### ISSUE TITLE
[Algo] Optimize bubble_sort.cpp

### ISSUE THREAD

**Issue by SaashaJoshi** [NITSkmOS/Algorithms#240]
Optimization of code.

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/20 ([Algo]: Add Bubble Sort in C++), https://github.com/NITSkmOS/Algorithms/issues/45 ([Algo] Binary Search [C++]), https://github.com/NITSkmOS/Algorithms/issues/222 ([Algo] Radix Sort [C++]), https://github.com/NITSkmOS/Algorithms/issues/22 ([Algo]: Add Heapsort in C++), and https://github.com/NITSkmOS/Algorithms/issues/62 ([Algo] Insertion Sort [C++]).

**Comment by MystikNinja** [comment]
What kind of optimizations are you thinking of here exactly?
