### ISSUE TITLE
[Data Structure] Stack in C++

### ISSUE THREAD

**Issue by Raamyy** [NITSkmOS/Algorithms#251]
I will go on implementing it :v:

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/58 ([Data Structure] Queue [C++]), https://github.com/NITSkmOS/Algorithms/issues/41 ([DataStructure] Stack [C++]), https://github.com/NITSkmOS/Algorithms/issues/54 ([Data Structure] Binary Search Tree [C++]), https://github.com/NITSkmOS/Algorithms/issues/48 ([Data Structure] AVL Tree [C++]), and https://github.com/NITSkmOS/Algorithms/issues/186 (euclidean_gcd in c++).

**Comment by sangamcse** [comment]
Duplicate of https://github.com/NITSkmOS/Algorithms/issues/41
