### ISSUE TITLE
[Algo] Merge Sort [C++]

### ISSUE THREAD

**Issue by megamayoy** [NITSkmOS/Algorithms#258]
https://en.wikipedia.org/wiki/Merge_sort

**Comment by megamayoy** [comment]
I would like to start working on this.  Will you please assign it to me ?

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/250 ([Algo] Quick Sort [C++]), https://github.com/NITSkmOS/Algorithms/issues/62 ([Algo] Insertion Sort [C++]), https://github.com/NITSkmOS/Algorithms/issues/222 ([Algo] Radix Sort [C++]), https://github.com/NITSkmOS/Algorithms/issues/20 ([Algo]: Add Bubble Sort in C++), and https://github.com/NITSkmOS/Algorithms/issues/45 ([Algo] Binary Search [C++]).

**Comment by d3vil0p3r** [comment]
@megamayoy I'm doing it 👍

**Comment by megamayoy** [comment]
@d3vil0p3r 

 did the repo maintainers assign it to you ?

**Comment by sangamcse** [comment]
@d3vil0p3r Read others comments also before opening a PR. @megamayoy has claimed the issue first.

**Comment by amrtaher1234** [comment]
I will do it
how to assign myself to an issue? I'm new here 🗡
