### ISSUE TITLE
[Request] Add Julia as a supported language

### ISSUE THREAD

**Issue by mariush2** [NITSkmOS/Algorithms#263]
This is a request to add Julia as one of the supported languages in this repo

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/159 (Add gitter badge), https://github.com/NITSkmOS/Algorithms/issues/2 (Add all sorting algorithms), https://github.com/NITSkmOS/Algorithms/issues/23 ([Algo]: Add Heapsort in C), https://github.com/NITSkmOS/Algorithms/issues/21 ([Algo]: Add Heapsort in Java), and https://github.com/NITSkmOS/Algorithms/issues/19 ([Algo]: Add Bubble Sort in C).

**Comment by sangamcse** [comment]
@mariush2 Definitely we can do this. What we have to do is:
1. Add a column in README table
2. Add in [Sample Run](https://github.com/NITSkmOS/Algorithms#sample-run)
3. Add the dependency requirement if any
4. Add to the .misc file
5. Check coala-bears which we can include in .coafile
6. Include in .editorconfig

**Comment by mariush2** [comment]
I have added the necessary changes to the README file. I am however not aware how to add the changes to .misc, .coafile and .editorconfig. Could you possible sort this out for me? To use Julia you need to install it from here: <a href="https://julialang.org/">https://julialang.org/</a>
