### ISSUE TITLE
[Algo] Bubble Sort (Python3 Implementation)

### ISSUE THREAD

**Issue by sameerchoubey** [NITSkmOS/Algorithms#282]
Please assign this to me.

Thanks

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/147 ([Algo] Merge Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/145 ([Algo] Selection Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/146 ([Algo] Quick Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/19 ([Algo]: Add Bubble Sort in C), and https://github.com/NITSkmOS/Algorithms/issues/149 ([Algo] Merge Sort [Java]).

**Comment by sangamcse** [comment]
Duplicate of https://github.com/NITSkmOS/Algorithms/issues/13.
Please go through the issue history before creating new issue.
