### ISSUE TITLE
Directory structure should be changed

### ISSUE THREAD

**Issue by AndyS12** [NITSkmOS/Algorithms#293]
For example: **mergersort** is implemented in python in directory **mergesort/Python**.
However **binary-search** directory structure is : Binary-search....then there are sub-directories listing programs in different languages.
I suggest keeping one directory structure will be good. The directory structure which I suggest is: 
[Algorithm-name]/[cpp | python | c | java]/[Algorithm-name].ext
So for merge-sort it should be:
**Merge-sort**
    ---- **cpp**  / merge-sort.cpp
    ---- **python** / merge-sort.py
    ---- **java** / merge-sort.java
    ---- **c** / merge-sort.c

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/56 ([Data Structure] Queue [C]), https://github.com/NITSkmOS/Algorithms/issues/55 ([Data Structure] Queue [Python]), https://github.com/NITSkmOS/Algorithms/issues/57 ([Data Structure] Queue [Java]), https://github.com/NITSkmOS/Algorithms/issues/47 ([Data Structure] AVL Tree [C]), and https://github.com/NITSkmOS/Algorithms/issues/234 ([Data Structure] Skip List [Python]).

**Comment by AndyS12** [comment]
Can you assign this to me?

**Comment by sangamcse** [comment]
I don't understand it. What you suggested is already there. Check again.
> Merge-sort
---- cpp / merge-sort.cpp
---- python / merge-sort.py
---- java / merge-sort.java
---- c / merge-sort.c

**Comment by AndyS12** [comment]
Sorry my mistake :)
