### ISSUE TITLE
[Algo] Counting Sort [C++]

### ISSUE THREAD

**Issue by paawan01** [NITSkmOS/Algorithms#299]
https://en.wikipedia.org/wiki/Counting_sort

**Comment by paawan01** [comment]
Realised while implementing radix sort that counting sort also doesn't exist for this repo.
@sangamcse Can you assign me this ?

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/258 ([Algo] Merge Sort [C++]), https://github.com/NITSkmOS/Algorithms/issues/250 ([Algo] Quick Sort [C++]), https://github.com/NITSkmOS/Algorithms/issues/62 ([Algo] Insertion Sort [C++]), https://github.com/NITSkmOS/Algorithms/issues/20 ([Algo]: Add Bubble Sort in C++), and https://github.com/NITSkmOS/Algorithms/issues/222 ([Algo] Radix Sort [C++]).

**Comment by koderproxy** [comment]
can i take this issue
