### ISSUE TITLE
[Algo] Add Knapsack problem [Python]

### ISSUE THREAD

**Issue by halderjoydeep** [NITSkmOS/Algorithms#305]
I want to implement this [algorithm](https://en.wikipedia.org/wiki/Knapsack_problem)

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/238 ([Algo] Coin Change Problem [Python]), https://github.com/NITSkmOS/Algorithms/issues/13 ([Algo]: Add Bubble Sort in python), https://github.com/NITSkmOS/Algorithms/issues/14 ([Algo]: Add Heapsort in Python), https://github.com/NITSkmOS/Algorithms/issues/302 ([Algo] Add Python Bubble Sort), and https://github.com/NITSkmOS/Algorithms/issues/43 ([Algo] Binary Search [Python]).

**Comment by Sartech-B** [comment]
I am taking this issue!

**Comment by sangamcse** [comment]
@Sartech-B did you care to read any comments in this issue?
