### ISSUE TITLE
bubble_sort c++ implementation was (accidentally) replaced with C version

### ISSUE THREAD

**Issue by coderobe** [NITSkmOS/Algorithms#316]
https://github.com/NITSkmOS/Algorithms/commit/6b2ca3080ba3af030b72e34890f1f2a8201c1285#diff-3d53538d5b15b0bc3e6e499c6b48d150 seems to have moved the wrong file (see commit diff)

**Comment by zeddmaxx** [comment]
Can I work on this?

**Comment by sangamcse** [comment]
https://github.com/NITSkmOS/Algorithms/blob/master/bubble_sort/Cpp/bubble_sort.cpp looks fine to me 😄

**Comment by sangamcse** [comment]
Fixed in https://github.com/NITSkmOS/Algorithms/commit/99cd8fbd0eaef3dc2de43f96f1d97d896ef31be9#diff-3d53538d5b15b0bc3e6e499c6b48d150
Related to https://github.com/NITSkmOS/Algorithms/issues/240

**Comment by coderobe** [comment]
not really, compare it to the implementation at https://github.com/NITSkmOS/Algorithms/commit/6b2ca3080ba3af030b72e34890f1f2a8201c1285#diff-3d53538d5b15b0bc3e6e499c6b48d150

**Comment by sangamcse** [comment]
See the current version
