### ISSUE TITLE
[Algo] Bubble Sort [Rust]

### ISSUE THREAD

**Issue by eloc3147** [NITSkmOS/Algorithms#358]
https://en.wikipedia.org/wiki/Binary_search_algorithm

I realize that Rust is not currently an accepted language, but I think it should be considered.
If necessary, I could contribute Rust code samples for every currently accepted algorithm.

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/147 ([Algo] Merge Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/145 ([Algo] Selection Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/19 ([Algo]: Add Bubble Sort in C), https://github.com/NITSkmOS/Algorithms/issues/146 ([Algo] Quick Sort [C]), and https://github.com/NITSkmOS/Algorithms/issues/296 ([Algo] Quick Sort [Elixir]).

**Comment by sangamcse** [comment]
Please read the documentation first. Before adding any algorithms in other languages in the repo, we have many settings to do. So please propose a language first. Thanks for your time.
