### ISSUE TITLE
[Algo] Counting Sort [C]

### ISSUE THREAD

**Issue by paawan01** [NITSkmOS/Algorithms#381]
https://en.wikipedia.org/wiki/Counting_sort

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/146 ([Algo] Quick Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/145 ([Algo] Selection Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/147 ([Algo] Merge Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/247 ([Algo] Insersion Sort [C]), and https://github.com/NITSkmOS/Algorithms/issues/19 ([Algo]: Add Bubble Sort in C).

**Comment by paawan01** [comment]
Would like to take this as well.
