### ISSUE TITLE
Binary Search Algo in Javascript

### ISSUE THREAD

**Issue by mandardeshpande** [NITSkmOS/Algorithms#405]

**Comment by mandardeshpande** [comment]
@sangamcse : can I work on this?

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/46 ([Algo] Binary Search [Java]), https://github.com/NITSkmOS/Algorithms/issues/44 ([Algo] Binary Search [C]), https://github.com/NITSkmOS/Algorithms/issues/43 ([Algo] Binary Search [Python]), https://github.com/NITSkmOS/Algorithms/issues/52 ([Data Structure] Binary Search Tree [Java]), and https://github.com/NITSkmOS/Algorithms/issues/149 ([Algo] Merge Sort [Java]).

**Comment by sangamcse** [comment]
We currently don't do javascript in this repo.
