### ISSUE TITLE
[Algo] Heap Sort [CPP]

### ISSUE THREAD

**Issue by 123vivekr** [NITSkmOS/Algorithms#422]
https://en.wikipedia.org/wiki/Heapsort

**Comment by 123vivekr** [comment]
@sangamcse Please assign this to me.

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/147 ([Algo] Merge Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/23 ([Algo]: Add Heapsort in C), https://github.com/NITSkmOS/Algorithms/issues/135 ([Algo] Shell Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/145 ([Algo] Selection Sort [C]), and https://github.com/NITSkmOS/Algorithms/issues/146 ([Algo] Quick Sort [C]).

**Comment by sangamcse** [comment]
Duplicate of https://github.com/NITSkmOS/Algorithms/issues/22
