### ISSUE TITLE
[Data Structure] AVL Tree [C]

### ISSUE THREAD

**Issue by sangamcse** [NITSkmOS/Algorithms#47]

**Comment by TheGamer007** [comment]
I'd like to take this up

**Comment by sangamcse** [comment]
@TheGamer007 Kindly go through contribution guidelines before any changes.

**Comment by TheGamer007** [comment]
I plan to include insertion, deletion, and in-order traversal, along with some utility methods required for implementing them. Would you like me to include any other operations on the DS?

**Comment by sangamcse** [comment]
Include pre and post traversal also. And don't forget to comment code and Update Readme table.

**Comment by sangamcse** [comment]
@TheGamer007, I have sent you an invitation. Accept it so that I can assign you the issue.
