### ISSUE TITLE
[Data Structure] AVL Tree [C++]

### ISSUE THREAD

**Issue by sangamcse** [NITSkmOS/Algorithms#48]

**Comment by paawan01** [comment]
Can I take this ?

**Comment by sangamcse** [comment]
@paawan01, I have sent you an invitation. Accept it so that I can assign you the issue. In case I forget it, feel free to ping me on gitter https://gitter.im/NITSkmOS/algo

**Comment by paawan01** [comment]
Thanks for the invitation. I have accepted it !
