### ISSUE TITLE
[Documentation] open source badge for README.md

### ISSUE THREAD

**Issue by yashasingh** [NITSkmOS/Algorithms#480]
More badges like [![Open Source Love](https://img.shields.io/badge/Open%20Source-%E2%9D%A4-red.svg)](https://github.com/NITSkmOS/Algorithms) can be added to the README.md :smile:

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/209 (Remove Codacy Badge and Include Travis Badge in README), and https://github.com/NITSkmOS/Algorithms/issues/159 (Add gitter badge).
