### ISSUE TITLE
[Algo] Selection sort [Cpp]

### ISSUE THREAD

**Issue by yashasingh** [NITSkmOS/Algorithms#482]
Repository does not include the cpp implementation for Selection sort.

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/145 ([Algo] Selection Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/247 ([Algo] Insersion Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/147 ([Algo] Merge Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/381 ([Algo] Counting Sort [C]), and https://github.com/NITSkmOS/Algorithms/issues/422 ([Algo] Heap Sort [CPP]).

**Comment by AndroidonEarth** [comment]
I'm working on this!
