### ISSUE TITLE
[Documentation] Incorrect indentation in README.md

### ISSUE THREAD

**Issue by yashasingh** [NITSkmOS/Algorithms#493]
On minutely observing [README.md  line 27](https://raw.githubusercontent.com/NITSkmOS/Algorithms/master/README.md), consists of TAB Spacing instead of default SPACE spacing. This will lead new contributors with indentation issues.

To-Do:
- [x] Correct the indentation and convert TAB spacing to SPACE spacing.

Level: Easy

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/480 ([Documentation] open source badge for README.md), and https://github.com/NITSkmOS/Algorithms/issues/486 (readme.md reference to implementation folder is missing).

**Comment by Mutmatt** [comment]
I can knock this one out if you don't mind

**Comment by Mutmatt** [comment]
How do we feel about adding a pre-commit hook like prettier to auto format files before a commit happens so this doesn't occur again.

https://prettier.io/docs/en/precommit.html

**Comment by sangamcse** [comment]
> How do we feel about adding a pre-commit hook like prettier to auto format files before a commit happens so this doesn't occur again.
> 
> https://prettier.io/docs/en/precommit.html

I will add MarkdownBear and SpaceConsistencyBear of coala.io for the md file
