### ISSUE TITLE
[Algo] Heap sort [java]

### ISSUE THREAD

**Issue by pentalpha** [NITSkmOS/Algorithms#508]
This repository is missing a Heap sort implementation using Java.

**Comment by pentalpha** [comment]
I wish to be assigned to this issue

**Comment by sangamcse** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/451 ([Algo] Merge Sort [Java]), https://github.com/NITSkmOS/Algorithms/issues/149 ([Algo] Merge Sort [Java]), https://github.com/NITSkmOS/Algorithms/issues/23 ([Algo] Heapsort [C]), https://github.com/NITSkmOS/Algorithms/issues/379 ([Algo] Counting Sort [java]), and https://github.com/NITSkmOS/Algorithms/issues/150 ([Algo] Quick Sort [Java]).

**Comment by sangamcse** [comment]
Duplicate of https://github.com/NITSkmOS/Algorithms/issues/21
