### ISSUE TITLE
[Data Structure] Binary Search Tree [C++]

### ISSUE THREAD

**Issue by sangamcse** [NITSkmOS/Algorithms#54]

**Comment by deepanshu-jain1999** [comment]
I wanna work on this issue.

**Comment by Divyansh00** [comment]
Please assign this to me

**Comment by sangamcse** [comment]
@deepanshu-jain1999 are you still working on this?

cc @Divyansh00, remind me if he is not replying in 1 or 2 days

**Comment by paawan01** [comment]
I'd like to work on this. Please let me know in case both @deepanshu-jain1999 and @Divyansh00 both don't respond :P

**Comment by gunanksood** [comment]
Hey please assign me this issue @sangamcse

**Comment by sangamcse** [comment]
@gunanksood there are multiple comments. Read them. They also want to work on this.
ping @deepanshu-jain1999, @Divyansh00 reply if you want to work on this. Otherwise, it will be assigned to @paawan01 or @gunanksood based on their interest.

**Comment by Divyansh00** [comment]
Sorry, I am not able to work on the issue right now as I am caught up with
my college exams. Will be able to look into it after 8th October.
