### ISSUE TITLE
[Algo] Insertion Sort [C++]

### ISSUE THREAD

**Issue by sangamcse** [NITSkmOS/Algorithms#62]

**Comment by Ankurk99** [comment]
```void insertionSort(int arr[], int n) 
{ 
   int i, c, j; 
   for (i = 1; i < n; i++) 
   { 
       c = arr[i]; 
       j = i-1; 
         while (j >= 0 && arr[j] > c) 
       { 
           arr[j+1] = arr[j]; 
           j = j-1; 
       } 
       arr[j+1] = c; 
   } 
} 
```

**Comment by prince8809** [comment]
C++
`#include<bits/stdc++.h>
using namespace std;
#define fori(x,n) for(int i=x;i<n;i++)
void insertionsort(int arr[],int n)
{
    for(int i=1;i<10;i++)
    {
        int temp;
        temp=arr[i];
        int x;
        for(int j=i;j>=0;j--)
        {
            if(temp<=arr[j])
             {
              arr[j]=arr[j-1];
              x=j;
             }
        }
        arr[x]=temp;
    }
}
int main()
{
    int n;
    cin>>n;
    int arr[n];
    for(int i=0;i<n;i++){cin>>arr[i];}
    insertionsort(arr,n);
    fori(0,n)
    {
        cout<<arr[i]<<" ";
    }
    return 0;
}
`

**Comment by Ankurk99** [comment]
I want to work on this.
